dataset: "GLOBE"

path:
  # corpus_path: "data/LJSpeech-1.1"
  # lexicon_path: "lexicon/librispeech-lexicon.txt"
  # raw_path: "./raw_data/LJSpeech"
  preprocessed_path: "/data/nzxyin/GLOBE/preprocess_default"
  splits_path: "/data/nzxyin/GLOBE/preprocess_default/splits/british_english_splits"